### ISSUE TITLE
Archos AC70 Hello?

### ISSUE THREAD

**Issue by woutervanh** [Dawnowl444/android_device_archos_ac50hello#1]
Hello,

Would you also have it (or be able to make it) for Archos Hello 7?

Grt,
Wouter

**Comment by Dawnowl444** [comment]
Hi,

Archos Hello 7 is a shitty device that can't be recovered if bricked (sp flash tools won't work because it needs auth files or something like that, I don't remember it all) so I advice you against doing it but if you're up to it here you go some image I packed up together when my AC70HELLO was still alive.
But once again I won't be taken responsible if you brick your device or if the image I'm giving you is non bootable (don't have a device to test it on) so best of luck but be extra carefull.
https://drive.google.com/file/d/17PoE6vBiLdHfL460xd1_rSHfHjNwOzVQ/view?usp=drive_link

**Comment by Dawnowl444** [comment]
Again use this with utterly most care because sp flash tools won't work so it's impossible to unbrick and it's hazardous to flash but here the stock rom that I used to work with https://firmwarefile.com/archos-hello-7

**Comment by woutervanh** [comment]
I just answered in the xda forum
https://xdaforums.com/t/archos-hello-7-ac70-flash-firmware.3981657/page-9
I want to get TWRP running on a stable way and think I have the tools for it. Just lacking some knowledge (and sources)

**Comment by Dawnowl444** [comment]
https://github.com/Dawnowl444/android_device_archos_ac50hello/blob/android-8.1/README.md#thanks- here's some reading if you want to dev. Those are the tutos I used to make the image for the AC50HELLO
